"""车辆管理 - Vehicle Model"""
from tortoise import fields

from .base import BaseModel, TimestampMixin


class Vehicle(BaseModel, TimestampMixin):
    """车辆信息表"""

    vn = fields.CharField(max_length=50, unique=True, index=True, description="车辆VN（去重主键）")
    vehicle_code = fields.CharField(max_length=50, index=True, description="车辆编号")
    vehicle_model = fields.CharField(max_length=100, description="车型项目")
    power_type = fields.CharField(max_length=50, description="动力类型")
    color = fields.CharField(max_length=50, description="颜色")
    has_controlled_items = fields.CharField(max_length=100, null=True, description="是否有管制物品")
    borrower = fields.CharField(max_length=50, null=True, description="借用人")
    borrow_expire_date = fields.DateField(null=True, description="借用到期时间")
    temp_plate_expire_date = fields.DateField(null=True, description="临牌到期时间")
    insurance_area = fields.CharField(max_length=100, null=True, description="保险区域")
    test_date = fields.DateField(null=True, description="试验日期")
    task_status = fields.CharField(max_length=50, null=True, description="任务状态")
    test_task = fields.CharField(max_length=100, null=True, description="试验任务")
    tester = fields.CharField(max_length=50, null=True, description="测试人员")
    driver = fields.CharField(max_length=50, null=True, description="驾驶人员")
    travel_status = fields.CharField(max_length=50, null=True, description="出差状态")
    test_city = fields.CharField(max_length=100, null=True, description="试验城市")
    exit_permit = fields.CharField(max_length=100, null=True, description="出门单")
    parking_spot = fields.CharField(max_length=100, null=True, description="停车位")
    location_info = fields.CharField(max_length=255, null=True, description="位置信息")
    latitude = fields.FloatField(null=True, description="纬度")
    longitude = fields.FloatField(null=True, description="经度")
    data_source = fields.CharField(max_length=50, default="manual", description="数据来源")
    temp_plate_area = fields.CharField(max_length=255, null=True, description="临牌区域")
    temp_plate_valid_area = fields.CharField(max_length=255, null=True, description="临牌有效区域")
    borrower_7day_rate = fields.FloatField(null=True, description="当前借用人7日利用率(%)")
    vehicle_status = fields.CharField(max_length=50, null=True, description="车辆状态")
    vehicle_status_note = fields.CharField(max_length=255, null=True, description="车辆状态备注")
    key_location = fields.CharField(max_length=100, null=True, description="钥匙位置")
    vehicle_manager = fields.CharField(max_length=50, null=True, description="车管")
    vehicle_manager_id = fields.CharField(max_length=50, null=True, description="车管ID")
    borrow_days = fields.IntField(null=True, description="借用天数")
    borrow_time = fields.CharField(max_length=50, null=True, description="借车时间")
    vehicle_phase = fields.CharField(max_length=50, null=True, description="车辆阶段")
    vehicle_model_config = fields.CharField(max_length=100, null=True, description="车型配置")
    temp_plate_info = fields.CharField(max_length=255, null=True, description="临牌信息")
    temp_plate_insurance_count = fields.IntField(null=True, description="临牌&保险办理次数")
    borrower_account = fields.CharField(max_length=50, null=True, description="借车人账号")
    borrower_id = fields.CharField(max_length=50, null=True, description="借车人ID")
    borrower_phone = fields.CharField(max_length=30, null=True, description="电话")
    dept_l1 = fields.CharField(max_length=100, null=True, description="一级部门")
    dept_l2 = fields.CharField(max_length=100, null=True, description="二级部门")
    storage_days = fields.IntField(null=True, description="在库时长")
    qr_code = fields.CharField(max_length=255, null=True, description="二维码")
    province = fields.CharField(max_length=50, null=True, description="车辆所在省")
    city = fields.CharField(max_length=50, null=True, description="车辆所在市")
    address_detail = fields.CharField(max_length=255, null=True, description="详细地址")
    is_monitored = fields.CharField(max_length=50, null=True, description="是否监控")
    monitor_method = fields.CharField(max_length=100, null=True, description="监控方式")
    is_first_vin_record = fields.CharField(max_length=50, null=True, description="是否VIN最早记录")
    battery_pack_status = fields.CharField(max_length=100, null=True, description="电池包状态")
    engine_no = fields.CharField(max_length=100, null=True, description="发动机号")
    battery_pack_trace = fields.CharField(max_length=255, null=True, description="电池包溯源码")
    front_motor_no = fields.CharField(max_length=100, null=True, description="前电机号")
    rear_motor_no = fields.CharField(max_length=100, null=True, description="后电机号")
    battery_pack_part_no = fields.CharField(max_length=100, null=True, description="电池包零件号")
    battery_pack_rated = fields.CharField(max_length=100, null=True, description="电池包额定电量")
    trial_plan = fields.CharField(max_length=255, null=True, description="试验策划")
    trial_plan_id = fields.CharField(max_length=100, null=True, description="试验策划ID")
    is_under_modification = fields.CharField(max_length=50, null=True, description="改制中")
    feishu_record_id = fields.CharField(max_length=100, null=True, description="飞书记录ID")

    class Meta:
        table = "vehicle"
